#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectionLogger.Droid.Resource", IsApplication=true)]

namespace ConnectionLogger.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::ConnectionLogger.Droid.Resource.String.library_name;
			global::PCLStorage.Resource.String.ApplicationName = global::ConnectionLogger.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::ConnectionLogger.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int change = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int error = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ok = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int start = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int stop = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int testnow = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int axisLayout = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int chartAreaLayout = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int chartTitle = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int gridLineLayout = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int iconView = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int label = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int legendHeader = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int legendItemsLayout = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int legendScrollView = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int legendViewGroup = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int rootLayout = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int seriesLayout = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int library_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
